"""added content table

Revision ID: 0d434b91828f
Revises: e8e41ad0aea4
Create Date: 2024-06-21 20:57:09.322675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '0d434b91828f'
down_revision: Union[str, None] = 'e8e41ad0aea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content',
    sa.Column('content_uid', sa.UUID(), nullable=False),
    sa.Column('course_uid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('content_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_data', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['course_uid'], ['courses.course_uid'], ),
    sa.PrimaryKeyConstraint('content_uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
        op.drop_table('content')
    # ### end Alembic commands ###
