"""add enrollment table

Revision ID: 17165b366ee0
Revises: 3b5c9c02783e
Create Date: 2024-07-07 19:49:34.309719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17165b366ee0'
down_revision: Union[str, None] = '3b5c9c02783e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollment',
    sa.Column('user_uid', sa.UUID(), nullable=False),
    sa.Column('course_uid', sa.UUID(), nullable=False),
    sa.Column('enrollment_date', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('user_uid', 'course_uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrollment')
    # ### end Alembic commands ###
