"""content table changes

Revision ID: 3b5c9c02783e
Revises: 849e2d6f5ff2
Create Date: 2024-06-24 13:54:10.797803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3b5c9c02783e'
down_revision: Union[str, None] = '849e2d6f5ff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('content_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('content', sa.Column('content_order', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content', 'content_order')
    op.drop_column('content', 'content_description')
    # ### end Alembic commands ###
