"""Added course table

Revision ID: 622a91385681
Revises: a530437635ee
Create Date: 2024-06-16 13:47:51.623110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '622a91385681'
down_revision: Union[str, None] = 'a530437635ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('course_uid', sa.UUID(), nullable=False),
    sa.Column('course_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('course_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('course_creator', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('course_image', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['course_creator'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('course_uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courses')
    # ### end Alembic commands ###
