"""changes in courses table

Revision ID: 849e2d6f5ff2
Revises: 0d434b91828f
Create Date: 2024-06-22 17:08:01.290035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '849e2d6f5ff2'
down_revision: Union[str, None] = '0d434b91828f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('course_price', sa.Float(), nullable=False))
    op.add_column('courses', sa.Column('is_published', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'is_published')
    op.drop_column('courses', 'course_price')
    # ### end Alembic commands ###
